<a href="https://colab.research.google.com/github/abel-wosula/Python/blob/main/Introduction_to_Pandas_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Python-Notebook-Banners/Exercise.png"  style="display: block; margin-left: auto; margin-right: auto;";/>
</div>

# Exercise: Introduction to Pandas


In this exercise, we test our understanding of basic Pandas functions.

## Learning objectives

By the end of this train, you should be able to:
* Create and display the data stored in a DataFrame.

## Exercises

### Import libraries

In [1]:
import pandas as pd
import numpy as np

### Exercise 1

Create a Pandas DataFrame from a dictionary. The dictionary keys should be `Crop`, `Yield_per_Acre`, and `Country`, and the values should be lists, as shown in the data below:

- Crop: `['Wheat', 'Corn', 'Rice', 'Soybean']`
- Yields per Acre (in tons): `[3, 4.5, 5, 2.8]`
- Country: `['USA', 'China', 'India', 'Brazil']`

In [4]:
crops_data = {
    'Crop': ['Wheat', 'Corn', 'Rice', 'Soybean'],
    'Yield_per_Acre': [3, 4.5, 5, 2.8],
    'Country': ['USA', 'China', 'India', 'Brazil']
}
crops_df = pd.DataFrame(crops_data)
print(crops_df)

      Crop  Yield_per_Acre Country
0    Wheat             3.0     USA
1     Corn             4.5   China
2     Rice             5.0   India
3  Soybean             2.8  Brazil

### Exercise 2

Using the DataFrame we created in **Exercise 1**, return only observations for index values 1 and 2 from the dataset.

In [5]:
# Your solution here...
crops_df.iloc[1:3]

   Crop  Yield_per_Acre Country
1  Corn             4.5   China
2  Rice             5.0   India

### Exercise 3

- Using the NumPy library, create a 3x2 array named `tree_array` to store information for different tree species as follows:

`[[30, 25], [60, 30], [25, 20]]`

- Use the array to create a DataFrame with the following columns: `Max_Height_m`, and `Growth_Rate_cm_per_year`, and the following index: `Maple`, `Pine` and `Birch`.

In [6]:
# Your solution here...
tree_array = np.array([[30, 25], [60, 30], [25, 20]])
columns = ['Max_Height_m', 'Growth_Rate_cm_per_year']
index = ['Maple', 'Pine', 'Birch']
tree_df = pd.DataFrame(data=tree_array, index=index, columns=columns)
print(tree_df)

       Max_Height_m  Growth_Rate_cm_per_year
Maple            30                       25
Pine             60                       30
Birch            25                       20

### Exercise 4

Using the DataFrame we created in **Exercise 3**, display the `Max_Height_m` and `Growth_Rate_cm_per_year` columns for the `Pine` tree.

In [7]:
# Your solution here...
tree_df.loc['Pine'][['Max_Height_m', 'Growth_Rate_cm_per_year']]

Max_Height_m               60
Growth_Rate_cm_per_year    30
Name: Pine, dtype: int64

### Exercise 5

- We have a dataset named `Animals.csv` that stores information about a variety of animal species. Use Pandas to load the CSV file into a DataFrame called `animals_df`.

- Display the first 5 rows of the DataFrame.

**NB:** Use this link to access the dataset: https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/Python/Animals.csv

In [9]:
# Your solution here...
animals_df = pd.read_csv("https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/Python/Animals.csv")
animals_df.head()

,Species,Average Lifespan (Years),Habitat,Conservation Status
0,African Elephant,60,Grasslands,Vulnerable
1,Bengal Tiger,15,Forests,Endangered
2,Blue Whale,80,Ocean,Endangered
3,Giant Panda,20,Temperate Forest,Vulnerable
4,Komodo Dragon,30,Islands,Vulnerable

### Exercise 6

Using the DataFrame we have created in **Exercise 5**, access and display information on animals that are listed as `Critically Endangered` in the `Conservation Status` column.

In [10]:
# Your solution here...
Critically_endangered = animals_df[animals_df['Conservation Status'] == 'Critically Endangered']
Critically_endangered = Critically_endangered.reset_index(drop=True)
Critically_endangered = Critically_endangered.drop(columns=['Conservation Status'])
Critically_endangered = Critically_endangered.rename(columns={'Animal Name': 'Animal_Name'})
Critically_endangered = Critically_endangered.rename(columns={'Animal Type': 'Animal_Type'})
Critically_endangered = Critically_endangered.rename(columns={'Number of Legs': 'Number_of_Legs'})
Critically_endangered = Critically_endangered.rename(columns={'Number of Curves': 'Number_of_Curves'})
Critically_endangered = Critically_endangered.rename(columns={'Number of Limbs': 'Number_of_Limbs'})
Critically_endangered = Critically_endangered.rename(columns={'Number of Teeth': 'Number_of_Teeth'})
Critically_endangered = Critically_endangered.rename(columns={'Number of Lives': 'Number_of_Lives'})
Critically_endangered = Critically_endangered.rename(columns={'Length (m)': 'Length_m'})
Critically_endangered = Critically_endangered.rename(columns={'Weight (kg)': 'Weight_kg'})
Critically_endangered = Critically_endangered.rename(columns={'Lifespan (years)': 'Lifespan_years'})
Critically_endangered = Critically_endangered.rename(columns={'Habitat': 'Habitat'})
Critically_endangered = Critically_endangered.rename(columns={'Diet': 'Diet'})
Critically_endangered = Critically_endangered.rename(columns={'Extinct': 'Extinct'})

## Solutions

### Exercise 1

In [2]:
# Creating a dictionary to hold agriculture data
agri_data = {
    'Crop': ['Wheat', 'Corn', 'Rice', 'Soybean'],
    'Yield_per_Acre': [3, 4.5, 5, 2.8],
    'Country': ['USA', 'China', 'India', 'Brazil']
}

# Creating a DataFrame from the agriculture data dictionary
agri_df = pd.DataFrame(agri_data)

# Printing the created DataFrame
print(agri_df)

      Crop  Yield_per_Acre Country
0    Wheat             3.0     USA
1     Corn             4.5   China
2     Rice             5.0   India
3  Soybean             2.8  Brazil

### Exercise 2

In [ ]:
agri_df.iloc[1:3]

In the solution above, we use `.iloc` for **position-based indexing** where we select rows based on their integer index.

We use the range 1 to 3 (not included). This returns the 2nd and the 3rd rows of data which correspond to `Corn` and `Rice` observations.

### Exercise 3

In [ ]:
# Creating a NumPy array to represent data for different tree species
tree_array = np.array([[30, 25], [60, 30], [25, 20]])

# Defining the column names for the DataFrame
columns = ['Max_Height_m', 'Growth_Rate_cm_per_year']

# Defining the index for the DataFrame which represents the names of the tree species
index = ['Maple', 'Pine', 'Birch']

# Creating a DataFrame from the NumPy array above
tree_df = pd.DataFrame(data=tree_array, index=index, columns=columns)

# Printing the created DataFrame
print(tree_df)

### Exercise 4

In [ ]:
tree_df.loc['Pine'][['Max_Height_m', 'Growth_Rate_cm_per_year']]

In the above solution, we have used the `.loc` method for **label-based indexing.**

The label `Pine` is used to select the row corresponding to the Pine tree. From this row, only the specified columns (`Max_Height_m` and `Growth_Rate_cm_per_year`) are selected and displayed.

### Exercise 5

In [ ]:
# Loading data from a CSV file named 'Animals.csv' into a DataFrame
animals_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/Python/Animals.csv')

# Displaying the first 5 rows of the DataFrame
animals_df.head()

The `.head(n)` function returns the first n rows, with the default being 5. This is useful for getting a quick view of the dataset.

### Exercise 6

In [ ]:
# Create a new DataFrame based on a condition
Critically_endangered = animals_df[animals_df['Conservation Status'] == 'Critically Endangered']

# Displaying the newly created DataFrame
Critically_endangered

**Conditional selection** is performed on the `animals_df` DataFrame. The condition `(animals_df['Conservation Status'] == 'Critically Endangered')` checks each row to see if the `Conservation Status` column's value is `Critically Endangered`. The rows that meet this condition are then used to create a new DataFrame named `Critically_endangered`.

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/refs/heads/master/ALX_banners/ALX_Navy.png"  style="width:140px";/>
</div>